### ISSUE TITLE
Configure rabbitmq_management Plugin Capabilities By Default

### ISSUE THREAD

**Issue by sean-horn** [chef/opscode-omnibus#702]
As a customer, I would like easy access to the rabbitmq_management plugin's abilities for deleting queues.

We should configure this plugin by default in the embedded cookbooks like https://gist.github.com/sean-horn/4b8c37a274b8ce5fb06f

Access to rabbitmqadmin abilities comes in handy when we have issues with an analytics system being offline.

**Comment by stevendanna** [comment]
@sean-horn We'd prefer to solve chef/chef-server#103 and not expose these tools to end users.  @metadave any thoughts from the analytics side?

**Comment by metadave** [comment]
I'm working on a `opscode-analytics-cmd` to remove queues/check depths without exposing additional rabbitmq commands (via Ruby client). This is mostly for customers who aren't using analytics. 

https://github.com/chef/omnibus-analytics/pull/208

**Comment by sean-horn** [comment]
Sounds good! Yeah, just the core function is perfectly fine.

**Comment by stevendanna** [comment]
@sean-horn It looks like the analytics team has a bug for the core functionality we need this for and that support has a clear procedure for how to enable the plugins in customer installations in the meantime.  Given that, I'm going to close this ticket rather than moving it to the new chef-server repository.  If I am mistaken, please let me know.
